import type { PatientDashboardData } from "../../types/patient";

// Placeholder data — no backend endpoint exists for all of this yet.
// Matches the wireframe specification in medops-patient-dashboard-enhanced.html
export const mockPatientDashboard: PatientDashboardData = {
  profile: {
    name: "John Smith",
    mrn: "MRN-2026-001245",
  },
  detailedProfile: {
    fullName: "John Smith",
    mrn: "MRN-2026-001245",
    dateOfBirth: "14 Mar 1985",
    gender: "Male",
    bloodGroup: "O+",
    phone: "+91 98765 43210",
    email: "john.smith@example.com",
    address: "24 Lodhi Gardens Road, New Delhi 110003",
    emergencyContact: "Anita Smith (Spouse) · +91 98765 11122",
    insuranceProvider: "Star Health",
    insurancePolicyNumber: "SH-88213",
  },
  unreadNotificationCount: 2,
  stats: [
    { id: "next-appointment", label: "Next Appointment", value: "Tomorrow", sublabel: "10:30 AM", linkLabel: "View details" },
    { id: "prescriptions", label: "Prescriptions", value: "3", sublabel: "Active", linkLabel: "View all" },
    { id: "lab-reports", label: "Lab Reports", value: "2", sublabel: "New results", linkLabel: "View reports" },
    { id: "medical-records", label: "Medical Records", value: "12", sublabel: "Documents", linkLabel: "View all" },
  ],
  upcomingAppointment: {
    day: "29",
    month: "AUG 2026",
    weekday: "SAT",
    doctorName: "Dr. Sarah Khan",
    specialty: "Cardiology",
    time: "10:30 AM",
    location: "Cardiology OPD, 3rd Floor",
    visitType: "Regular check-up",
  },
  allAppointments: [
    {
      id: "apt-1",
      dateTime: "29 Aug 2026, 10:30 AM",
      doctorName: "Dr. Sarah Khan",
      department: "Cardiology",
      status: "UPCOMING",
      location: "Cardiology OPD, 3rd Floor",
      reason: "Regular check-up",
    },
    {
      id: "apt-2",
      dateTime: "20 Aug 2026, 11:00 AM",
      doctorName: "Dr. Ahmed Ali",
      department: "General Medicine",
      status: "COMPLETED",
      location: "Room 102, 1st Floor",
      reason: "Flu follow-up",
    },
    {
      id: "apt-3",
      dateTime: "10 Aug 2026, 09:30 AM",
      doctorName: "Dr. Priya Mehta",
      department: "Dermatology",
      status: "COMPLETED",
      location: "Skin Care Clinic, 2nd Floor",
      reason: "Skin allergy review",
    },
    {
      id: "apt-4",
      dateTime: "28 Jul 2026, 04:00 PM",
      doctorName: "Dr. Vikram Singh",
      department: "Orthopedics",
      status: "CANCELLED",
      location: "Ortho Suite 4B",
      reason: "Knee pain consultation",
    },
    {
      id: "apt-5",
      dateTime: "15 Jul 2026, 02:00 PM",
      doctorName: "Dr. Sarah Khan",
      department: "Cardiology",
      status: "COMPLETED",
      location: "Cardiology OPD, 3rd Floor",
      reason: "ECG routine review",
    },
    {
      id: "apt-6",
      dateTime: "02 Jul 2026, 09:00 AM",
      doctorName: "Dr. Ahmed Ali",
      department: "General Medicine",
      status: "COMPLETED",
      location: "Room 102, 1st Floor",
      reason: "Annual health check",
    },
  ],
  recentAppointments: [
    { id: "apt-2", dateTime: "20 Aug 2026, 11:00 AM", doctorName: "Dr. Ahmed Ali", department: "General Medicine", status: "COMPLETED" },
    { id: "apt-3", dateTime: "10 Aug 2026, 09:30 AM", doctorName: "Dr. Priya Mehta", department: "Dermatology", status: "COMPLETED" },
    { id: "apt-4", dateTime: "28 Jul 2026, 04:00 PM", doctorName: "Dr. Vikram Singh", department: "Orthopedics", status: "CANCELLED" },
  ],
  prescriptions: [
    {
      id: "rx-1",
      medicationName: "Atorvastatin",
      dosage: "10mg · 1 tablet nightly",
      instructions: "Take with water before bed",
      prescribedBy: "Dr. Sarah Khan",
      refillsRemaining: 2,
      status: "ACTIVE",
    },
    {
      id: "rx-2",
      medicationName: "Metformin",
      dosage: "500mg · 2 tablets daily with meals",
      instructions: "Take with breakfast and dinner",
      prescribedBy: "Dr. Ahmed Ali",
      refillsRemaining: 0,
      status: "RENEWAL_NEEDED",
    },
    {
      id: "rx-3",
      medicationName: "Cetirizine",
      dosage: "10mg · 1 tablet as needed",
      instructions: "Take once daily when allergic symptoms occur",
      prescribedBy: "Dr. Priya Mehta",
      refillsRemaining: 4,
      status: "ACTIVE",
    },
  ],
  labReports: [
    {
      id: "lab-1",
      title: "Complete Blood Count (CBC)",
      date: "25 Aug 2026",
      orderedBy: "Dr. Ahmed Ali",
      status: "NEW",
      category: "Hematology",
    },
    {
      id: "lab-2",
      title: "Lipid Profile",
      date: "20 Aug 2026",
      orderedBy: "Dr. Sarah Khan",
      status: "NEW",
      category: "Biochemistry",
    },
    {
      id: "lab-3",
      title: "HbA1c",
      date: "10 Jun 2026",
      orderedBy: "Dr. Ahmed Ali",
      status: "REVIEWED",
      category: "Endocrinology",
    },
    {
      id: "lab-4",
      title: "Thyroid Panel",
      date: "02 Mar 2026",
      orderedBy: "Dr. Sarah Khan",
      status: "REVIEWED",
      category: "Endocrinology",
    },
  ],
  medicalDocuments: [
    { id: "doc-1", title: "Cardiology Visit Summary", date: "20 Aug 2026", provider: "Dr. Ahmed Ali", type: "SUMMARY", fileSize: "245 KB" },
    { id: "doc-2", title: "Dermatology Consultation Notes", date: "10 Aug 2026", provider: "Dr. Priya Mehta", type: "NOTE", fileSize: "180 KB" },
    { id: "doc-3", title: "Lipid Profile Report", date: "20 Aug 2026", provider: "Lab Services", type: "LAB", fileSize: "512 KB" },
    { id: "doc-4", title: "Orthopedics Discharge Note", date: "28 Jul 2026", provider: "Dr. Vikram Singh", type: "DISCHARGE", fileSize: "310 KB" },
    { id: "doc-5", title: "Cardiology Follow-up Summary", date: "15 Jul 2026", provider: "Dr. Sarah Khan", type: "SUMMARY", fileSize: "220 KB" },
    { id: "doc-6", title: "HbA1c Report", date: "10 Jun 2026", provider: "Lab Services", type: "LAB", fileSize: "420 KB" },
    { id: "doc-7", title: "General Medicine Visit Summary", date: "02 Jul 2026", provider: "Dr. Ahmed Ali", type: "SUMMARY", fileSize: "195 KB" },
    { id: "doc-8", title: "Thyroid Panel Report", date: "02 Mar 2026", provider: "Lab Services", type: "LAB", fileSize: "380 KB" },
  ],
  billing: {
    outstandingBalance: "₹1,850",
    dueInvoiceCount: 1,
    paidThisYear: "₹12,400",
    paidInvoiceCount: 4,
    insuranceProvider: "Star Health",
    policyStatus: "Policy active",
    invoices: [
      { id: "inv-1", invoiceNumber: "INV-2108", date: "20 Aug 2026", description: "General Medicine consult", amount: "₹1,850", status: "DUE" },
      { id: "inv-2", invoiceNumber: "INV-2087", date: "10 Aug 2026", description: "Dermatology consult", amount: "₹1,200", status: "PAID", receiptUrl: "/receipts/INV-2087.pdf" },
      { id: "inv-3", invoiceNumber: "INV-1994", date: "28 Jul 2026", description: "Orthopedics — cancelled", amount: "₹0", status: "WAIVED" },
      { id: "inv-4", invoiceNumber: "INV-1932", date: "15 Jul 2026", description: "Cardiology follow-up", amount: "₹2,600", status: "PAID", receiptUrl: "/receipts/INV-1932.pdf" },
    ],
  },
  faqs: [
    {
      id: "faq-1",
      question: "How do I reschedule an appointment?",
      answer: 'Go to Appointments, find the visit, and select "Reschedule / Cancel." You can choose a new date and time or cancel outright.',
    },
    {
      id: "faq-2",
      question: "How long does it take to get lab results?",
      answer: 'Most results are available within 24–48 hours and appear under Lab Reports with a "New" label once ready.',
    },
    {
      id: "faq-3",
      question: "Can I request a prescription refill online?",
      answer: 'Yes — open Prescriptions and select "Request Refill" on the medication you need. Your doctor will review and approve it.',
    },
    {
      id: "faq-4",
      question: "How do I update my insurance information?",
      answer: 'Visit My Profile and select "Edit Profile" to update your insurance provider and policy details.',
    },
  ],
  notifications: [
    { id: "1", title: "Lab report is ready", description: "Your CBC report is now available.", timeAgo: "2 hours ago", unread: true },
    { id: "2", title: "Appointment confirmed", description: "Your appointment with Dr. Sarah Khan is confirmed.", timeAgo: "1 day ago", unread: false },
  ],
  healthMetrics: [
    { id: "bp", label: "Blood Pressure", value: "120/80 mmHg", status: "Normal" },
    { id: "blood-group", label: "Blood Group", value: "O+", status: "Positive" },
    { id: "weight", label: "Weight", value: "72 kg", status: "Updated 2 months ago" },
  ],
};

