import type { DoctorDashboardData } from "../../types/doctor";

export const mockDoctorDashboard: DoctorDashboardData = {
  profile: {
    name: "Dr. Sarah Mitchell",
    specialty: "Cardiology",
    licenseNumber: "MD-94812",
    email: "s.mitchell@medops.health",
    phoneNumber: "+1 (555) 432-8765",
  },
  unreadAlertsCount: 4,
  stats: [
    {
      id: "today-patients",
      label: "Today's Schedule",
      value: "12 Patients",
      sublabel: "4 completed · 8 remaining",
      trend: "+2 vs yesterday",
      trendPositive: true,
    },
    {
      id: "waiting-room",
      label: "Waiting Room",
      value: "3 Patients",
      sublabel: "Avg wait time: 14 mins",
      trend: "Optimal flow",
      trendPositive: true,
    },
    {
      id: "lab-results",
      label: "Pending Lab Reviews",
      value: "5 Reports",
      sublabel: "2 require urgent follow-up",
      trend: "Action needed",
      trendPositive: false,
    },
    {
      id: "satisfaction",
      label: "Patient Satisfaction",
      value: "98.4%",
      sublabel: "Based on 142 reviews",
      trend: "+1.2% this month",
      trendPositive: true,
    },
  ],
  todayAppointments: [
    {
      id: "apt-101",
      time: "09:00 AM",
      patientName: "James Wilson",
      patientMrn: "MRN-2026-004812",
      age: 58,
      gender: "Male",
      reason: "Hypertension Routine Follow-up",
      type: "In-Person",
      status: "COMPLETED",
    },
    {
      id: "apt-102",
      time: "09:45 AM",
      patientName: "Elena Rostova",
      patientMrn: "MRN-2026-009314",
      age: 44,
      gender: "Female",
      reason: "Echocardiogram Review & Holter Analysis",
      type: "In-Person",
      status: "IN_PROGRESS",
    },
    {
      id: "apt-103",
      time: "10:30 AM",
      patientName: "Marcus Vance",
      patientMrn: "MRN-2026-001290",
      age: 62,
      gender: "Male",
      reason: "Post-Angioplasty 3-Month Check",
      type: "In-Person",
      status: "WAITING",
    },
    {
      id: "apt-104",
      time: "11:15 AM",
      patientName: "Amara Chen",
      patientMrn: "MRN-2026-007823",
      age: 35,
      gender: "Female",
      reason: "Palpitations / ECG Consultation",
      type: "Telehealth",
      status: "CONFIRMED",
    },
    {
      id: "apt-105",
      time: "01:30 PM",
      patientName: "David Miller",
      patientMrn: "MRN-2026-003419",
      age: 51,
      gender: "Male",
      reason: "Lipid Profile & Statin Dosage Titration",
      type: "In-Person",
      status: "CONFIRMED",
    },
  ],
  patientQueue: [
    {
      id: "q-1",
      patientName: "Marcus Vance",
      roomNumber: "Exam Room 3",
      checkInTime: "10:15 AM",
      chiefComplaint: "Slight shortness of breath upon exertion",
      priority: "HIGH",
    },
    {
      id: "q-2",
      patientName: "Amara Chen",
      roomNumber: "Virtual Room A",
      checkInTime: "10:25 AM",
      chiefComplaint: "Intermittent fluttering sensation",
      priority: "NORMAL",
    },
    {
      id: "q-3",
      patientName: "Robert Hayes",
      roomNumber: "Triage Bay 2",
      checkInTime: "10:28 AM",
      chiefComplaint: "BP reading 178/104 at intake",
      priority: "URGENT",
    },
  ],
  pendingLabReviews: [
    {
      id: "lab-1",
      patientName: "Elena Rostova",
      testName: "Comprehensive Metabolic Panel + Troponin-T",
      orderedDate: "Aug 26, 2026",
      status: "NORMAL",
    },
    {
      id: "lab-2",
      patientName: "David Miller",
      testName: "Advanced Lipid Panel (LDL-P & ApoB)",
      orderedDate: "Aug 25, 2026",
      status: "ABNORMAL",
    },
    {
      id: "lab-3",
      patientName: "Robert Hayes",
      testName: "Urgent Serum Electrolytes & Creatinine",
      orderedDate: "Today, 10:30 AM",
      status: "CRITICAL",
    },
  ],
};
